apiVersion: v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-vol
              mountPath: /var/jenkins
      volumes:
        - name: jenkins-vol
          emptyDir: {}