apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
    labels:
      kiali_wizard: weighted_routing
    name: public-gateway
    namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP