apiVersion: v1
kind: Secret
metadata:
  name: mysq-user
type: Opaque
data:
  password: cGFzcw==

---
#MYSQL_ROOT_PASSWORD
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root
type: Opaque
data:
  password: bXlzcWxwYXNz